##
##  Makefile -- Build procedure for sample coffee Apache module
##  Autogenerated via ``apxs -n coffee -g''.
##

builddir=.
top_srcdir=/usr/local/apache-httpd/httpd-2.4.10
top_builddir=/usr/local/apache-httpd/httpd-2.4.10
include /usr/local/apache-httpd/httpd-2.4.10/build/special.mk

#   the used tools
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_coffee.o mod_coffee.lo mod_coffee.slo mod_coffee.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/coffee

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

